[project]
name = 'blank-project'
description = 'Create a project from scratch: Start from a blank scaffold for your next Clarity contract'
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.core]
path = 'contracts/core.clar'
clarity_version = 3
epoch = 3.0

[contracts.extension-trait]
path = 'contracts/extension-trait.clar'
clarity_version = 3
epoch = 3.0

[contracts.proposal-trait]
path = 'contracts/proposal-trait.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
